### PR TITLE
Delete avatar

### PR DESCRIPTION
**Pull request by HusseinTaha**
Migrate Coffee to TS
Add delete api
Fix tests

### CODE REVIEW

**Comment by HusseinTaha** [comment]
Closes #24 
Closes #22

**Comment by j3k0** [comment]
Wow, that was fast. Reminder about the thing we talked about, `sharp": "^0.30.3` is not a `devDependency` (those are things only required to developers of the module -- running test, building the distribution --, not to run).

**Comment by HusseinTaha** [comment]
Yeah you are right. I saw the lwip was there.. so added the same for sharp. But since it's required to run the app so we need it in the dependencies.
I'll change that.

**Comment by j3k0** [comment]
All is good here! Thanks good job!

Remaining issues are that our CircleCI configuration is deprecated and that `npm run lint` is far from passing... We'll fix that sometime...

**Pull request merged**
